name: self-hosted-workflow
on:
  workflow_dispatch:

jobs:
  test-cvmfs:
    runs-on: ngt
    container: registry.cern.ch/docker.io/library/ubuntu:22.04
    steps:
      - name: test cvmfs
        run: sleep 60; ls /cvmfs/atlas.cern.ch/repo
  test-gpu:
    runs-on: ngt-gpu
    container: registry.cern.ch/docker.io/rochaporto/gpu_burn
    steps:
      - name: nvidia-smi
        run: |
          nvidia-smi
      - name: gpuburn
        run: |
          /app/gpu_burn 60
