name: self-hosted-workflow
on:
  workflow_dispatch:

jobs:
  test-cvmfs:
    runs-on: arc-rochaporto
    steps:
      - name: test cvmfs
        run: ls /cvmfs/atlas.cern.ch/repo
  test-gpu:
    runs-on: arc-rochaporto-gpu
    container: mooseontehloose/gpuburn:v1.0.0
    steps:
      - name: gpuburn
        run: |
          nvidia-smi
          ./gpu_burn 60
